export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_ALREADY_COMPLETED: "TASK_ALREADY_COMPLETED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
